version: '3.8'

services:
  postgres_db:
    image: postgres:16
    container_name: cakely_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: cakely
      POSTGRES_PASSWORD: cakely_pwd
      POSTGRES_DB: cakely_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
