CREATE TYPE order_status AS ENUM ('Pendiente', 'Preparando', 'Listo', 'Entregado');
CREATE TYPE payment_method AS ENUM ('Tarjeta', 'Efectivo', 'Bizum', 'Transferencia');
CREATE TYPE product_type AS ENUM ('Tarta', 'Galletas', 'Cupcakes', 'Macarons', 'Otros');
CREATE TYPE payment_status AS ENUM ('Pendiente', 'Pagado', 'Cancelado');

CREATE TABLE orders (
    order_id SERIAL PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_contact TEXT NOT NULL,
    order_date TIMESTAMP NOT NULL,
    delivery_date TIMESTAMP,
    order_status order_status NOT NULL,
    description TEXT,
    amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    product_type product_type NOT NULL,
    customization_details TEXT,
    quantity INT NOT NULL CHECK (quantity > 0),
    size_or_weight TEXT NOT NULL,
    flavor TEXT NOT NULL,
    allergy_information TEXT,

    total_price NUMERIC(10, 2) NOT NULL CHECK (total_price >= 0),
    payment_status payment_status NOT NULL,
    payment_method payment_method NOT NULL,

    notes TEXT,
    order_history JSONB,
    images JSONB DEFAULT '[]'::jsonb
);

-- Índices para búsquedas comunes
CREATE INDEX idx_order_status ON orders(order_status);
CREATE INDEX idx_order_date ON orders(order_date);
CREATE INDEX idx_delivery_date ON orders(delivery_date);

-- Datos de prueba
INSERT INTO orders (
    customer_name, 
    customer_contact, 
    order_date, 
    delivery_date, 
    order_status, 
    description, 
    amount, 
    product_type, 
    customization_details, 
    quantity, 
    size_or_weight, 
    flavor, 
    allergy_information, 
    total_price, 
    payment_status, 
    payment_method, 
    notes, 
    order_history,
    images
)
VALUES
('Ana Gómez', 
 'ana.gomez@example.com', 
 '2025-01-15 09:00:00', 
 '2025-01-20 14:00:00', 
 'Pendiente', 
 'Tarta de cumpleaños temática', 
 35.00, 
 'Tarta', 
 'Decoración de unicornio', 
 1, 
 '1.5 kg', 
 'Vainilla', 
 'Sin frutos secos', 
 35.00, 
 'Pendiente', 
 'Tarjeta', 
 'Entregar antes de las 14:00', 
 '{"status_changes": [{"status": "Pendiente", "timestamp": "2025-01-15T09:00:00"}]}',
 '[{"id": "img1", "url": "https://example.com/images/ana1.jpg"}]'
),
('Luis Fernández', 
 'luis.fernandez@example.com', 
 '2025-01-12 10:30:00', 
 '2025-01-17 16:00:00', 
 'Preparando', 
 'Galletas con iniciales', 
 20.00, 
 'Galletas', 
 'Forma redonda con iniciales grabadas', 
 24, 
 'N/A', 
 'Chocolate', 
 'Sin gluten', 
 20.00, 
 'Pagado', 
 'Bizum', 
 'Confirmar antes de la entrega', 
 '{"status_changes": [{"status": "Pendiente", "timestamp": "2025-01-12T10:30:00"}, {"status": "Preparando", "timestamp": "2025-01-14T15:00:00"}]}',
 '[{"id": "img1", "url": "https://example.com/images/luis1.jpg"}, {"id": "img2", "url": "https://example.com/images/luis2.jpg"}]'
),
('Carla Ruiz', 
 'carla.ruiz@example.com', 
 '2025-01-10 08:45:00', 
 '2025-01-15 11:00:00', 
 'Listo', 
 'Cupcakes para fiesta infantil', 
 30.00, 
 'Cupcakes', 
 'Decoración de animales', 
 12, 
 'N/A', 
 'Fresa', 
 'Sin lactosa', 
 30.00, 
 'Pagado', 
 'Efectivo', 
 'Entrega en cajas individuales', 
 '{"status_changes": [{"status": "Pendiente", "timestamp": "2025-01-10T08:45:00"}, {"status": "Preparando", "timestamp": "2025-01-12T12:00:00"}, {"status": "Listo", "timestamp": "2025-01-14T18:00:00"}]}',
 '[]'
),
('Diego Martínez', 
 'diego.martinez@example.com', 
 '2025-01-18 14:00:00', 
 '2025-01-25 13:00:00', 
 'Entregado', 
 'Caja de macarons surtidos', 
 18.00, 
 'Macarons', 
 'Sabores surtidos: chocolate, pistacho, frambuesa', 
 18, 
 'N/A', 
 'Varios', 
 'Sin alérgenos', 
 18.00, 
 'Pagado', 
 'Transferencia', 
 'Entregado en caja decorativa', 
 '{"status_changes": [{"status": "Pendiente", "timestamp": "2025-01-18T14:00:00"}, {"status": "Preparando", "timestamp": "2025-01-20T10:00:00"}, {"status": "Listo", "timestamp": "2025-01-24T15:00:00"}, {"status": "Entregado", "timestamp": "2025-01-25T13:00:00"}]}',
 '[{"id": "img1", "url": "https://example.com/images/diego1.jpg"}]'
),
('Laura Sánchez', 
 'laura.sanchez@example.com', 
 '2025-01-14 16:00:00', 
 '2025-01-22 17:30:00', 
 'Preparando', 
 'Pedido mixto: tarta y cupcakes', 
 45.00, 
 'Otros', 
 'Tarta temática de fútbol y cupcakes decorados', 
 1, 
 '2 kg', 
 'Chocolate y vainilla', 
 'Sin lactosa', 
 45.00, 
 'Pendiente', 
 'Tarjeta', 
 'Confirmar diseño antes de continuar', 
 '{"status_changes": [{"status": "Pendiente", "timestamp": "2025-01-14T16:00:00"}, {"status": "Preparando", "timestamp": "2025-01-16T09:00:00"}]}',
 '[{"id": "img1", "url": "https://example.com/images/laura1.jpg"}, {"id": "img2", "url": "https://example.com/images/laura2.jpg"}]'
);
